# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  - push
  - pull_request

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        java:
          - 8
          - 17
        jdk:
          - temurin
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.jdk }}
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Run tests
        run: sbt --batch test publishM2 mavenTests
        # run: sbt --batch "testOnly nl.jarmoniuk.download.DownloadMojoTest"

